export function buildDormHubLifecycleOptions(input: Record<string, any>) {
  const { state, me, refs, queries, queryClient, setLiveMessages, chatRuntime, settingsSaveActions, view, noticeAuthMutations } =
    input;

  return {
    activeTab: state.activeTab,
    socketOptions: {
      dormId: queries.meQuery.data?.dormId,
      meId: queries.meQuery.data?.id,
      queryClient,
      socketRef: refs.socketRef,
      lastActiveTabRef: refs.lastActiveTabRef,
      chatAtBottomRef: refs.chatAtBottomRef,
      chatForceBottomOnNextLayoutRef: refs.chatForceBottomOnNextLayoutRef,
      pendingNewChatIdsRef: refs.pendingNewChatIdsRef,
      setLiveMessages,
      setNewChatHintCount: state.setNewChatHintCount,
      setChatNewerCursor: chatRuntime.setChatNewerCursor,
      setChatHasNewer: chatRuntime.setChatHasNewer,
      setNoticePopup: state.setNoticePopup,
      autoReadByTypeMutation: noticeAuthMutations.autoReadByTypeMutation,
    },
    settingsAutoSaveOptions: {
      activeTab: state.activeTab,
      isLeader: Boolean(me?.isLeader),
      hasMe: Boolean(me),
      botOtherEditing: state.botOtherEditing,
      botOtherTextareaRef: refs.botOtherTextareaRef,
      name: state.name,
      language: state.language,
      dormNameInput: state.dormNameInput,
      botNameInput: state.botNameInput,
      botOtherContent: state.botOtherContent,
      botSettingsInput: state.botSettingsInput,
      memberDescriptionsInput: state.memberDescriptionsInput,
      avatarFile: state.avatarFile,
      botAvatarFile: state.botAvatarFile,
      ...settingsSaveActions,
    },
    chatTabSyncOptions: {
      activeTab: state.activeTab,
      chatScrollRef: refs.chatScrollRef,
      chatMessageRefs: refs.chatMessageRefs,
      chatAutoScrolledRef: refs.chatAutoScrolledRef,
      chatAtBottomRef: refs.chatAtBottomRef,
      pendingNewChatIdsRef: refs.pendingNewChatIdsRef,
      setNewChatHintCount: state.setNewChatHintCount,
      resetChatToLatest: chatRuntime.resetChatToLatest,
    },
    tabAutoReadOptions: {
      activeTab: state.activeTab,
      lastAutoReadTabRef: refs.lastAutoReadTabRef,
      mutate: (type: any) => noticeAuthMutations.autoReadByTypeMutation.mutate(type),
    },
    tabPrefetchOptions: {
      billsHasNextPage: Boolean(queries.billsQuery.hasNextPage),
      billsIsFetchingNextPage: queries.billsQuery.isFetchingNextPage,
      fetchNextBills: () => queries.billsQuery.fetchNextPage(),
      billsRowCount: view.billsRows.length,
      unpaidBillCount: view.unpaidBillCount,
      paidBillGroupCount: view.groupedPaidBills.length,
      dutyHasNextPage: Boolean(queries.dutyAllQuery.hasNextPage),
      dutyIsFetchingNextPage: queries.dutyAllQuery.isFetchingNextPage,
      fetchNextDuty: () => queries.dutyAllQuery.fetchNextPage(),
      pendingDutyGroupCount: view.groupedPendingDuties.length,
      doneDutyGroupCount: view.groupedDoneDuties.length,
      notificationRowCount: view.notificationRows.length,
      noticeHasNextPage: Boolean(queries.notificationsQuery.hasNextPage),
      noticeIsFetchingNextPage: queries.notificationsQuery.isFetchingNextPage,
      fetchNextNotices: () => queries.notificationsQuery.fetchNextPage(),
      unpaidListRef: refs.billUnpaidListRef,
      paidListRef: refs.billPaidListRef,
    },
  };
}
