
import React, { useEffect } from 'react';

<<<<<<<< HEAD:components/dorm-app/hooks/use-tab-auto-read.ts
import type { ActiveTab } from '@/components/dorm-app/types';
========
import type { ActiveTab } from '@/components/dorm-hub/ui-types';
>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-tab-auto-read.ts

type NoticeType = 'chat' | 'bill' | 'duty' | 'settings' | 'dorm' | 'leader';

export function useTabAutoRead(options: {
  activeTab: ActiveTab;
  lastAutoReadTabRef: React.MutableRefObject<ActiveTab>;
  mutate: (type: NoticeType) => void;
}) {
  const { activeTab, lastAutoReadTabRef, mutate } = options;

  useEffect(() => {
    if (lastAutoReadTabRef.current === activeTab) return;
    lastAutoReadTabRef.current = activeTab;
    if (activeTab === 'chat') {
      mutate('chat');
      return;
    }
    if (activeTab === 'wallet') {
      mutate('bill');
      return;
    }
    if (activeTab === 'duty') {
      mutate('duty');
      return;
    }
    if (activeTab === 'settings') {
      mutate('settings');
      mutate('dorm');
      mutate('leader');
    }
  }, [activeTab, lastAutoReadTabRef, mutate]);
}

<<<<<<<< HEAD:components/dorm-app/hooks/use-tab-auto-read.ts
========

>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-tab-auto-read.ts
