
<<<<<<<< HEAD:components/dorm-app/hooks/use-dorm-socket.ts
import React, { useEffect } from 'react';
========
import { useEffect } from 'react';
import type { Dispatch, MutableRefObject, SetStateAction } from 'react';
>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-dorm-socket.ts
import { io, type Socket } from 'socket.io-client';
import type { QueryClient } from '@tanstack/react-query';

import { mergeChatMessages, tabForNotificationType } from '../ui-helpers';
import type { ActiveTab, ChatMessage } from '../ui-types';

type AutoReadType = 'chat' | 'bill' | 'duty' | 'settings' | 'dorm' | 'leader';

export function useDormSocket(options: {
  dormId: number | null | undefined;
  meId: number | null | undefined;
  queryClient: QueryClient;
  socketRef: MutableRefObject<Socket | null>;
  lastActiveTabRef: MutableRefObject<ActiveTab>;
  chatAtBottomRef: MutableRefObject<boolean>;
  chatForceBottomOnNextLayoutRef: MutableRefObject<boolean>;
  pendingNewChatIdsRef: MutableRefObject<Set<number>>;
  setLiveMessages: Dispatch<SetStateAction<ChatMessage[]>>;
  setNewChatHintCount: Dispatch<SetStateAction<number>>;
  setChatNewerCursor: Dispatch<SetStateAction<number | null>>;
  setChatHasNewer: Dispatch<SetStateAction<boolean>>;
  setNoticePopup: Dispatch<SetStateAction<{ title: string; content: string } | null>>;
  autoReadByTypeMutation: { mutate: (type: AutoReadType) => void };
}) {
  const {
    dormId,
    meId,
    queryClient,
    socketRef,
    lastActiveTabRef,
    chatAtBottomRef,
    chatForceBottomOnNextLayoutRef,
    pendingNewChatIdsRef,
    setLiveMessages,
    setNewChatHintCount,
    setChatNewerCursor,
    setChatHasNewer,
    setNoticePopup,
    autoReadByTypeMutation,
  } = options;

  useEffect(() => {
    if (!dormId) return;

    let mounted = true;

    const init = async () => {
      let initOk = false;
      for (let attempt = 0; attempt < 3; attempt += 1) {
        try {
          const initResp = await fetch('/api/socket-init', {
            method: 'GET',
            cache: 'no-store',
            headers: { Accept: 'application/json' },
          });
          if (initResp.ok) {
            initOk = true;
            break;
          }
        } catch (error) {
          console.error('[socket-init] failed', error);
        }
        await new Promise((resolve) => setTimeout(resolve, 250 * (attempt + 1)));
      }
      if (!mounted) return;

      const socket = io({
        path: '/api/socket',
        reconnection: true,
        reconnectionAttempts: Infinity,
        reconnectionDelay: 500,
        reconnectionDelayMax: 3000,
      });
      if (!initOk) {
        console.warn('[socket-init] not ready after retries, continue with socket reconnection');
      }
      socket.emit('join', dormId);

      socket.on('chat:new', (message: ChatMessage) => {
        const isChatTab = lastActiveTabRef.current === 'chat';
        const shouldCountAsNew = Boolean(isChatTab && meId && message.userId !== meId);
        if (isChatTab && chatAtBottomRef.current) {
          chatForceBottomOnNextLayoutRef.current = true;
        }
        setLiveMessages((prev) => mergeChatMessages(prev, [message]));
        if (shouldCountAsNew && !chatAtBottomRef.current) {
          pendingNewChatIdsRef.current.add(message.id);
          setNewChatHintCount(pendingNewChatIdsRef.current.size);
        }
        setChatNewerCursor((prev) => (prev && prev > message.id ? prev : message.id));
        setChatHasNewer(false);
      });

      socket.on('duty:changed', () => {
        void queryClient.invalidateQueries({ queryKey: ['duty', 'all'] });
      });
      socket.on('bill:changed', () => {
        void queryClient.invalidateQueries({ queryKey: ['bills'] });
      });

      socket.on('notification:new', (payload: { userId?: number; type?: string; title: string; content: string }) => {
        if (!meId || (payload.userId && payload.userId !== meId)) return;
        const targetTab = tabForNotificationType(payload.type);
        if (targetTab && lastActiveTabRef.current === targetTab) {
          const typeToRead = payload.type as AutoReadType;
          autoReadByTypeMutation.mutate(typeToRead);
          if (targetTab === 'settings') {
            void queryClient.invalidateQueries({ queryKey: ['me'] });
          }
          return;
        }
        setNoticePopup({ title: payload.title, content: payload.content });
        setTimeout(() => {
          setNoticePopup((current) => (current && current.title === payload.title && current.content === payload.content ? null : current));
        }, 5000);
      });

      socket.on('notification:changed', (payload: { type?: string }) => {
        void queryClient.invalidateQueries({ queryKey: ['notifications'] });
        void queryClient.invalidateQueries({ queryKey: ['notifications-unread'] });
        void queryClient.invalidateQueries({ queryKey: ['notifications-chat-anchor'] });
        void queryClient.invalidateQueries({ queryKey: ['chat-anchor-id'] });
        if (payload?.type === 'settings' || payload?.type === 'dorm' || payload?.type === 'leader') {
          void queryClient.invalidateQueries({ queryKey: ['me'] });
        }
      });

      socket.on('status:changed', () => {
        void queryClient.invalidateQueries({ queryKey: ['status'] });
      });

      socketRef.current = socket;
    };

    void init();

    return () => {
      mounted = false;
      socketRef.current?.disconnect();
      socketRef.current = null;
    };
  }, [
    autoReadByTypeMutation,
    chatAtBottomRef,
    chatForceBottomOnNextLayoutRef,
    dormId,
    lastActiveTabRef,
    meId,
    pendingNewChatIdsRef,
    queryClient,
    setChatHasNewer,
    setChatNewerCursor,
    setLiveMessages,
    setNewChatHintCount,
    setNoticePopup,
    socketRef,
  ]);
}
