
import { useMutation, type QueryClient } from '@tanstack/react-query';
import type { Socket } from 'socket.io-client';
import type { MutableRefObject } from 'react';

import { apiRequest } from '@/lib/client-api';
<<<<<<<< HEAD:components/dorm-app/hooks/use-notice-auth-mutations.ts
import type { NotificationFilter } from '@/components/dorm-app/types';
import React from "react";
========
import type { NotificationFilter } from '@/components/dorm-hub/ui-types';
>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-notice-auth-mutations.ts

type NoticeType = 'chat' | 'bill' | 'duty' | 'settings' | 'dorm' | 'leader';

export function useNoticeAuthMutations(options: {
  queryClient: QueryClient;
  notificationFilter: NotificationFilter;
  socketRef: MutableRefObject<Socket | null>;
}) {
  const { queryClient, notificationFilter, socketRef } = options;

  const readNoticeMutation = useMutation({
    mutationFn: (id: number) => apiRequest(`/api/notifications/${id}/read`, { method: 'PUT', body: JSON.stringify({}) }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['notifications'] });
      void queryClient.invalidateQueries({ queryKey: ['notifications-unread'] });
    },
  });

  const readSelectedNoticeMutation = useMutation({
    mutationFn: (payload: { selectAll: boolean; ids: number[] }) =>
      apiRequest('/api/notifications/batch', {
        method: 'POST',
        body: JSON.stringify({
          action: 'read',
          status: notificationFilter,
          selectAll: payload.selectAll,
          ids: payload.ids,
          types: [],
        }),
      }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['notifications'] });
      void queryClient.invalidateQueries({ queryKey: ['notifications-unread'] });
    },
  });

  const deleteSelectedNoticeMutation = useMutation({
    mutationFn: (payload: { selectAll: boolean; ids: number[] }) =>
      apiRequest('/api/notifications/batch', {
        method: 'POST',
        body: JSON.stringify({
          action: 'delete',
          status: notificationFilter,
          selectAll: payload.selectAll,
          ids: payload.ids,
          types: [],
        }),
      }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['notifications'] });
      void queryClient.invalidateQueries({ queryKey: ['notifications-unread'] });
    },
  });

  const autoReadByTypeMutation = useMutation({
    mutationFn: (type: NoticeType) =>
      apiRequest('/api/notifications/batch', {
        method: 'POST',
        body: JSON.stringify({
          action: 'read',
          status: 'unread',
          selectAll: true,
          ids: [],
          types: [type],
        }),
      }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['notifications'] });
      void queryClient.invalidateQueries({ queryKey: ['notifications-unread'] });
      void queryClient.invalidateQueries({ queryKey: ['notifications-chat-anchor'] });
      void queryClient.invalidateQueries({ queryKey: ['chat-anchor-id'] });
    },
  });

  const deleteNoticeMutation = useMutation({
    mutationFn: (id: number) => apiRequest(`/api/notifications/${id}`, { method: 'DELETE', body: JSON.stringify({}) }),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['notifications'] });
      void queryClient.invalidateQueries({ queryKey: ['notifications-unread'] });
    },
  });

  const logoutMutation = useMutation({
    mutationFn: () => apiRequest<{ success: true }>('/api/logout', { method: 'POST', body: JSON.stringify({}) }),
    onSuccess: () => {
      socketRef.current?.disconnect();
      socketRef.current = null;
      queryClient.clear();
      if (typeof window !== 'undefined') window.location.assign('/login');
    },
  });

  const deleteAccountMutation = useMutation({
    mutationFn: () => apiRequest<{ success: true }>('/api/users/me', { method: 'DELETE', body: JSON.stringify({}) }),
    onSuccess: () => {
      socketRef.current?.disconnect();
      socketRef.current = null;
      queryClient.clear();
      if (typeof window !== 'undefined') window.location.assign('/login');
    },
  });

  return {
    readNoticeMutation,
    readSelectedNoticeMutation,
    deleteSelectedNoticeMutation,
    autoReadByTypeMutation,
    deleteNoticeMutation,
    logoutMutation,
    deleteAccountMutation,
  };
}

<<<<<<<< HEAD:components/dorm-app/hooks/use-notice-auth-mutations.ts
========

>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-notice-auth-mutations.ts
