
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';

import { apiRequest } from '@/lib/client-api';
import type { BillSummary, CursorPage, DormState, DutyItem, MePayload, NotificationPayload } from '@/lib/types';
<<<<<<<< HEAD:components/dorm-app/hooks/use-queries.ts
import { BILL_PAGE_LIMIT, CHAT_PAGE_LIMIT } from '@/components/dorm-app/constants';
import type { ChartPoint, LineGranularity, LineSeries, NotificationFilter, PeriodType } from '@/components/dorm-app/types';

export function useQueries(options: {
========
import { BILL_PAGE_LIMIT, CHAT_PAGE_LIMIT } from '@/components/dorm-hub/ui-constants';
import type { ChartPoint, LineGranularity, LineSeries, NotificationFilter, PeriodType } from '@/components/dorm-hub/ui-types';

export function useDormQueries(options: {
>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-dorm-queries.ts
  notificationFilter: NotificationFilter;
  billPeriodType: PeriodType;
  billYear: string;
  billPeriodMarker: number;
  billLineGranularity: LineGranularity;
  dutyPeriodType: PeriodType;
  dutyYear: string;
  dutyPeriodMarker: number;
  dutyLineGranularity: LineGranularity;
}) {
  const {
    notificationFilter,
    billPeriodType,
    billYear,
    billPeriodMarker,
    billLineGranularity,
    dutyPeriodType,
    dutyYear,
    dutyPeriodMarker,
    dutyLineGranularity,
  } = options;

  const meQuery = useQuery({
    queryKey: ['me'],
    queryFn: () => apiRequest<MePayload>('/api/users/me'),
  });
  const authReady = Boolean(meQuery.data?.id);

  const dutyAllQuery = useInfiniteQuery({
    queryKey: ['duty', 'all'],
    queryFn: ({ pageParam }) =>
      apiRequest<CursorPage<DutyItem>>(`/api/duty?scope=all&limit=8${pageParam ? `&cursor=${pageParam}` : ''}`),
    initialPageParam: null as number | null,
    getNextPageParam: (lastPage) => lastPage.nextCursor,
    enabled: authReady,
  });

  const billsQuery = useInfiniteQuery({
    queryKey: ['bills'],
    queryFn: ({ pageParam }) =>
      apiRequest<CursorPage<BillSummary>>(`/api/bills?limit=${BILL_PAGE_LIMIT}${pageParam ? `&cursor=${pageParam}` : ''}`),
    initialPageParam: null as number | null,
    getNextPageParam: (lastPage) => lastPage.nextCursor,
    enabled: authReady,
  });

  const chatQuery = useInfiniteQuery({
    queryKey: ['chat'],
    queryFn: ({ pageParam }) =>
      apiRequest<CursorPage<{ id: number; userId: number; userName: string; content: string; createdAt: string }>>(
        `/api/chat?limit=${CHAT_PAGE_LIMIT}${pageParam ? `&cursor=${pageParam}` : ''}`,
      ),
    initialPageParam: null as number | null,
    getNextPageParam: (lastPage) => lastPage.nextCursor,
    enabled: authReady,
  });

  const statusQuery = useQuery({
    queryKey: ['status'],
    queryFn: () => apiRequest<Array<{ userId: number; state: DormState }>>('/api/status'),
    enabled: authReady,
  });

  const notificationsQuery = useInfiniteQuery({
    queryKey: ['notifications', notificationFilter],
    queryFn: ({ pageParam }) =>
      apiRequest<CursorPage<NotificationPayload>>(
        `/api/notifications?status=${notificationFilter}&limit=10${pageParam ? `&cursor=${pageParam}` : ''}`,
      ),
    initialPageParam: null as number | null,
    getNextPageParam: (lastPage) => lastPage.nextCursor,
    enabled: authReady,
  });

  const notificationsUnreadQuery = useQuery({
    queryKey: ['notifications-unread'],
    queryFn: () => apiRequest<CursorPage<NotificationPayload>>('/api/notifications?status=unread&limit=60'),
    enabled: authReady,
  });

  const chatAnchorNoticeQuery = useQuery({
    queryKey: ['notifications-chat-anchor'],
    queryFn: () => apiRequest<{ oldestUnreadChatNotificationTime: string | null }>('/api/notifications/chat-anchor'),
    enabled: authReady,
  });

  const chatAnchorQuery = useQuery({
    queryKey: ['chat-anchor-id', chatAnchorNoticeQuery.data?.oldestUnreadChatNotificationTime],
    queryFn: () =>
      apiRequest<{ anchorId: number | null }>(
        `/api/chat/anchor?from=${encodeURIComponent(chatAnchorNoticeQuery.data?.oldestUnreadChatNotificationTime || '')}`,
      ),
    enabled: authReady && Boolean(chatAnchorNoticeQuery.data?.oldestUnreadChatNotificationTime),
  });

  const billStatsQuery = useQuery({
    queryKey: ['stats-bills', billPeriodType, billYear, billPeriodMarker, billLineGranularity],
    queryFn: () =>
      apiRequest<{ pieData: ChartPoint[]; lineData: ChartPoint[]; categoryLineSeries: LineSeries[] }>(
        `/api/stats/bills?periodType=${billPeriodType}&year=${encodeURIComponent(
          billYear,
        )}&marker=${billPeriodMarker}&lineGranularity=${billLineGranularity}`,
      ),
    enabled: authReady,
  });

  const dutyStatsQuery = useQuery({
    queryKey: ['stats-duty', dutyPeriodType, dutyYear, dutyPeriodMarker, dutyLineGranularity],
    queryFn: () =>
      apiRequest<{ pieData: ChartPoint[]; memberPieData: ChartPoint[]; lineData: ChartPoint[]; memberLineSeries: LineSeries[] }>(
        `/api/stats/duty?periodType=${dutyPeriodType}&year=${encodeURIComponent(
          dutyYear,
        )}&marker=${dutyPeriodMarker}&lineGranularity=${dutyLineGranularity}`,
      ),
    enabled: authReady,
  });

  return {
    authReady,
    meQuery,
    dutyAllQuery,
    billsQuery,
    chatQuery,
    statusQuery,
    notificationsQuery,
    notificationsUnreadQuery,
    chatAnchorNoticeQuery,
    chatAnchorQuery,
    billStatsQuery,
    dutyStatsQuery,
  };
}

<<<<<<<< HEAD:components/dorm-app/hooks/use-queries.ts
========

>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/hooks/use-dorm-queries.ts
