
import { Camera } from 'lucide-react';
import type { LanguageCode } from '@/lib/i18n';
import { LANG_OPTIONS } from '@/lib/i18n';
import { LIMITS } from '@/lib/limits';

<<<<<<<< HEAD:components/dorm-app/settings/user-settings-section.tsx
import { resolveAvatar } from '../helpers';
import { SettingsSection } from '../settings-section';
========
import { resolveAvatar } from '../ui-helpers';
import { SettingsCard } from '../settings-card';
>>>>>>>> 7ebe914 (fix: fix simple errors generated by idea):components/dorm-hub/settings/user-settings-card.tsx
import React from "react";

export function UserSettingsCard(props: {
  t: any;
  me: any;
  meId: number;
  folded: boolean;
  toggleLabel: string;
  onToggle: () => void;
  avatarInputRef: React.RefObject<HTMLInputElement>;
  changeAvatarTitle: string;
  setAvatarFile: (file: File | null) => void;
  name: string;
  setName: (v: string) => void;
  language: LanguageCode;
  setLanguage: (v: LanguageCode) => void;
  tryApplyLimitedInput: (key: string, value: string, max: number, message: string, apply: (safeValue: string) => void) => boolean;
  eText: any;
}) {
  const { t, me, meId, folded, toggleLabel, onToggle, avatarInputRef, changeAvatarTitle, setAvatarFile, name, setName, language, setLanguage, tryApplyLimitedInput, eText } = props;

  return (
    <SettingsCard title={t.userInfo} folded={folded} onToggle={onToggle} toggleLabel={toggleLabel} className={`glass-card sleep-depth-mid rounded-3xl ${folded ? 'px-7 py-4 md:px-9 md:py-4' : 'p-7 md:p-9'}`}>
      <div className="grid grid-cols-1 md:grid-cols-[220px_1fr] gap-8 md:gap-10 items-center mt-6">
        <div className="flex flex-col items-center text-center">
          <div className="relative w-36 h-36 md:w-40 md:h-40">
            <div className="w-full h-full rounded-full overflow-hidden ring-4 ring-white/40 shadow-2xl">
              <img src={resolveAvatar(me?.avatarPath, meId || 0)} alt={t.userInfo} className="w-full h-full object-cover" />
            </div>
            <button type="button" title={changeAvatarTitle} onClick={() => avatarInputRef.current?.click()} className="absolute right-1 bottom-1 w-10 h-10 rounded-full accent-bg shadow-xl flex items-center justify-center border-2 border-white/70">
              <span className="sr-only">{changeAvatarTitle}</span>
              <Camera className="w-5 h-5 text-white" />
            </button>
          </div>
          <input ref={avatarInputRef} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setAvatarFile(e.target.files?.[0] || null)} />
        </div>

        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 md:gap-6">
            <input className="w-full p-3 rounded-xl glass-card custom-field" value={name} onChange={(e) => tryApplyLimitedInput('user_name', e.target.value, LIMITS.USER_NAME, eText.nameTooLong, setName)} placeholder={t.nickname} />
            <select className="w-full p-3 rounded-xl glass-card custom-field" value={language} onChange={(e) => setLanguage(e.target.value as LanguageCode)}>
              {LANG_OPTIONS.map((opt) => (<option key={opt.value} value={opt.value}>{opt.label}</option>))}
            </select>
            <div className="glass-card rounded-xl px-4 py-3 lg:col-span-2">
              <p className="text-[11px] text-muted font-bold mb-1">Email</p>
              <p className="font-black break-all">{me?.email || '-'}</p>
            </div>
          </div>
        </div>
      </div>
    </SettingsCard>
  );
}
